### ISSUE TITLE
Bluetooth don't work

### ISSUE THREAD

**Issue by LeslieChou7** [2black0/EFI-ThinkCentre-M720Q#1]
Hello, I use your EFI(commit  f089ed48686a553dd5fb7f6abe98baea41533d1a) with nothing problem. But when I update the EFI(commit  3f66f1dbc3750a76178375964e036d5fa1674817), the bluetooth don't work. I just move the platform info from the older EFI to the new. And I think there are problems about usb driver or setting. Thx.

**Comment by 2black0** [comment]
idk how to fix it, bluetooth only working when wifi disable / off

**Comment by 2black0** [comment]
thanks for opening this issue, I rarely use bluetooth, will check it first :)

**Comment by LeslieChou7** [comment]
I check my hardware and drivers again, and it seems like that because I use broadcom wireless utility without any related drivers. When I add BrcmBluetoothInjector.kext, BrcmPatchRAM3.kext and BrcmFirmwareData.kext under the drivers directory, It can work no problem after reboot. (And I notice you are using intel wireless utility so I don't ensure is it useful to you.)  :)
